export { resend } from './resend';
export { sendConfirmationEmail } from './sendConfirmation';
export type { SendConfirmationEmailOptions } from './sendConfirmation';
export { sendAcceptanceEmail } from './sendAcceptance';
export type { SendAcceptanceEmailOptions } from './sendAcceptance';
export { sendAbelencoEmail } from './sendAbelenco';
export type { SendAbelencoEmailOptions } from './sendAbelenco';
export { generateOrderDetails } from './generateOrderDetails';
export { generateConfirmationEmailHtml, generateConfirmationEmailText, generateAcceptanceEmailHtml, generateAcceptanceEmailText, generateAbelencoEmailHtml, generateAbelencoEmailText } from './templates';
export type { ConfirmationEmailData, AcceptanceEmailData, AbelencoEmailData } from './templates';
